language: php

dist: bionic
sudo: false

git:
    depth: 1

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - ZABBIX_VERSION=2.4.0
    - ZABBIX_VERSION=2.4.8
    - ZABBIX_VERSION=3.0.0
    - ZABBIX_VERSION=3.4.15
    - ZABBIX_VERSION=4.0.0
    - ZABBIX_VERSION=4.4.4

jobs:
    fast_finish: true
    include:
        - php: 5.3
          dist: precise
          env: ZABBIX_VERSION=2.4.0
        - php: 5.3
          dist: precise
          env: ZABBIX_VERSION=2.4.8
        - php: 5.4
          dist: trusty
          env: ZABBIX_VERSION=2.4.0
        - php: 5.4
          dist: trusty
          env: ZABBIX_VERSION=2.4.8
        - php: 5.4
          dist: precise
          env: ZABBIX_VERSION=3.0.0
        - php: 5.4
          dist: precise
          env: ZABBIX_VERSION=3.4.15
        - php: 5.4
          dist: precise
          env: ZABBIX_VERSION=4.0.0
        - php: 5.4
          dist: precise
          env: ZABBIX_VERSION=4.4.4
        - php: 5.5
          dist: trusty
          env: ZABBIX_VERSION=2.4.0
        - php: 5.5
          dist: trusty
          env: ZABBIX_VERSION=2.4.8
        - php: 5.5
          dist: precise
          env: ZABBIX_VERSION=3.0.0
        - php: 5.5
          dist: precise
          env: ZABBIX_VERSION=3.4.15
        - php: 5.5
          dist: precise
          env: ZABBIX_VERSION=4.0.0
        - php: 5.5
          dist: precise
          env: ZABBIX_VERSION=4.4.4
        - php: 5.6
          dist: trusty
          env: ZABBIX_VERSION=2.4.0
        - php: 5.6
          dist: trusty
          env: ZABBIX_VERSION=2.4.8
        - php: 5.6
          dist: precise
          env: ZABBIX_VERSION=3.0.0
        - php: 5.6
          dist: precise
          env: ZABBIX_VERSION=3.4.15
        - php: 5.6
          dist: precise
          env: ZABBIX_VERSION=4.0.0
        - php: 5.6
          dist: precise
          env: ZABBIX_VERSION=4.4.4
        - php: 7.0
          dist: trusty
          env: ZABBIX_VERSION=2.4.0
        - php: 7.0
          dist: trusty
          env: ZABBIX_VERSION=2.4.8
        - php: 7.0
          dist: precise
          env: ZABBIX_VERSION=3.0.0
        - php: 7.0
          dist: precise
          env: ZABBIX_VERSION=3.4.15
        - php: 7.0
          dist: precise
          env: ZABBIX_VERSION=4.0.0
        - php: 7.0
          dist: precise
          env: ZABBIX_VERSION=4.4.4

cache:
    directories:
        - $HOME/.composer

before_install:
    - |
      # Install dependencies
      sudo apt-get update
      sudo apt-get install apache2 sqlite3
    - |
      # Download zabbix server frontend
      stty cols 120
      mkdir -p /opt/zabbix
      wget -qO- wget -qO- https://repo.zabbix.com/zabbix/${ZABBIX_VERSION%.*}/ubuntu/pool/main/z/zabbix/zabbix_${ZABBIX_VERSION}.orig.tar.gz | tar xvzf - -C /opt/zabbix zabbix-${ZABBIX_VERSION}/frontends/php zabbix-${ZABBIX_VERSION}/database/sqlite3/
      ln -s /opt/zabbix/zabbix-$ZABBIX_VERSION/frontends/php/ /opt/zabbix/frontend
    - |
      # Config php-fpm server
      sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
      echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
      sudo chown -R travis:travis /var/lib/apache2/fastcgi
      ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - |
      # Config apache2 server
      sudo a2enmod rewrite actions proxy proxy_fcgi fastcgi alias
      sudo sed -ri 's#DocumentRoot /var/www/html#DocumentRoot /opt/zabbix/frontend/#; s#(</VirtualHost>)#\tProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/opt/zabbix/frontend/$1\n\t<Directory "/opt/zabbix/frontend">\n\t\tRequire all granted\n\t\tAllowOverride All\n\t</Directory>\n\1#' /etc/apache2/sites-available/000-default.conf
      cat /etc/apache2/sites-available/000-default.conf
      sudo systemctl restart apache2

    - |
      # Config sqlite database
      sqlite3 /opt/zabbix/zabbix.db < /opt/zabbix/zabbix-$ZABBIX_VERSION/database/sqlite3/schema.sql
      sqlite3 /opt/zabbix/zabbix.db < /opt/zabbix/zabbix-$ZABBIX_VERSION/database/sqlite3/data.sql
      echo -e '<?php\nglobal $DB;\n$DB["TYPE"] = "SQLITE3";\n$DB["DATABASE"] = "/opt/zabbix/zabbix.db";\n$ZBX_SERVER = "PhpZabbixApi";\n$ZBX_SERVER_PORT = "10051";\n$ZBX_SERVER_NAME = "Test Server";\n$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;\n' > /opt/zabbix/frontend/conf/zabbix.conf.php

install:
    - php ./build/build.php
    - composer install --prefer-dist --optimize-autoloader --classmap-authoritative --no-interaction --no-scripts

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpunit --testdox

